[versions]
kotlin = "2.4.0"
serialization = "1.11.0"
coroutines = "1.11.0"

[libraries]
# Serialization
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# Coroutines
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

[plugins]
# Serialization
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
